TRSV2-175: forgotten password
uktrade/trade-remedies-public pull request #139
Opened 2022-05-11 10:57 UTC by KnowYourLines

2022-05-11 15:18 UTC, chris-pettinga requested changes
Looks good, just some comments on HTML/JS reusability

2022-05-11 15:18 UTC, chris-pettinga commented on trade_remedies_public/templates/password/password_reset_requested.html
> +<br/><br/>
Does the prototype have these breaks?

2022-05-11 15:18 UTC, chris-pettinga commented on trade_remedies_public/templates/password/password_reset_requested.html
> +<p>We've sent an email to the email address you provided. Use the link in the email to reset your password.</p>
Do you need to use the govuk-body class?

2022-05-11 15:18 UTC, chris-pettinga commented on trade_remedies_public/templates/password/reset_password_request.html
> +<br/><br/>
Same comment as above

2022-05-12 12:59 UTC, KnowYourLines commented on trade_remedies_public/config/middleware.py
> +    if kwargs.get("user_pk") and kwargs.get("token"):
We don't want a back button on the reset_password page for the happy path, but we can't get that URL if those two arguments are not present. An error will be thrown by `reverse`. This ensures we only try to reverse the URL if the arguments are present.

2022-05-12 14:13 UTC, KnowYourLines commented on trade_remedies_public/templates/password/password_reset_requested.html
> +<br/><br/>
`base_with_form.html` is a bit of premature optimization in this case as it isn't used in other parts of the prototype.

2022-05-12 14:14 UTC, KnowYourLines commented on trade_remedies_public/templates/password/password_reset_requested.html
> +<br/><br/>
```            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                    <h1 class="govuk-fieldset__heading">
                        {% block fieldset_heading %}{% endblock fieldset_heading %}
                    </h1>
                </legend>
            </fieldset>
```
This isn't common across other pages.

2022-05-12 15:22 UTC, KnowYourLines commented on trade_remedies_public/templates/password/reset_password_request.html
> +<br/><br/>
base_with_form.html does not fit this template so might be a bit of a premature optimization

2022-05-17 10:57 UTC, chris-pettinga approved these changes

2022-05-17 14:15 UTC, merged