branding changes
uktrade/trade-remedies-public pull request #14
Opened 2020-11-18 11:18 UTC by jwgulley

These are changes for making updates to the branding as described in TRLST-169.  Tipu has kindly reviewed the result and declared himself happy with it..  This PR is for review only at this stage, but with a view to it being approved and applied when the branding update is required.

Please review, specifically examining the changes to the fixtures, as it is not clear whether these are needed.

Known Issues

These changes do not include:
- updates to any documents - e.g. letter of authority templates or email templates;
- updates to the database - see the ticket comment for details, also the fixture changes may be relevant.

2020-11-18 12:08 UTC, markhigham approved these changes
LGTM. You could've potentially used those partial templates where you've made text changes. Or perhaps added them to context processor and used {{ TRID_full_name }}

2020-11-20 14:26 UTC, davecharles requested changes
I think these templates have been missed:
```
trade_remedies_public/templates/cases/submissions/questionnaire/tasklist.html
trade_remedies_public/templates/cases/submissions/invite/tasklist.html
trade_remedies_public/templates/cases/submissions/invite/submit.html
```

2020-11-20 14:26 UTC, davecharles commented on trade_remedies_public/templates/partials/TRID_abbreviation.html
> +TRA
Do we still need this file?

2020-11-20 14:26 UTC, davecharles commented on trade_remedies_public/templates/partials/TRID_full_name.html
> +Trade Remedies Authority
Do we still need this file?

2020-11-23 16:52 UTC, Luisella21 commented
Do we need to add ORGANISATION_INITIALISM and ORGANISATION_NAME to the env file?

2020-11-25 16:08 UTC, jwgulley commented
> I think these templates have been missed:
> 
> ```
> trade_remedies_public/templates/cases/submissions/questionnaire/tasklist.html
> trade_remedies_public/templates/cases/submissions/invite/tasklist.html
> trade_remedies_public/templates/cases/submissions/invite/submit.html
> ```
Thanks, David.

2020-11-25 16:11 UTC, jwgulley commented
> Do we need to add ORGANISATION_INITIALISM and ORGANISATION_NAME to the env file?
Thank-you - adding them to local.env.example.

2020-11-25 16:55 UTC, davecharles approved these changes
LGTM

2020-11-26 11:21 UTC, rossmiller requested changes
Please address the other comments and update the readme with instructions for the new env vars.

2020-11-26 11:21 UTC, rossmiller commented on trade_remedies_public/core/templatetags/organisation_initialism.py
> +Template tag to display organisation name and organisation initialism
Please change text to "Template tag to display organisation initialism"

2020-11-26 11:21 UTC, rossmiller commented on trade_remedies_public/core/tests.py
> +                    "name": settings.ORGANISATION_INITIALISM + " Document",
Please use a f-string here rather than +

2020-11-26 14:04 UTC, jwgulley commented on trade_remedies_public/core/tests.py
> +                    "name": settings.ORGANISATION_INITIALISM + " Document",
Thanks - done.

2020-12-01 10:53 UTC, rossmiller commented on local.env.example
> +# Parameters for branding
Change to:
```
ORGANISATION_NAME = "Organisation name placeholder"
ORGANISATION_INITIALISM = "PLACEHOLDER"
```

2020-12-01 15:03 UTC, jwgulley commented on local.env.example
> +# Parameters for branding
done

2020-12-01 15:03 UTC, jwgulley commented on trade_remedies_public/core/templatetags/organisation_initialism.py
> +Template tag to display organisation name and organisation initialism
done

2020-12-02 12:36 UTC, rossmiller approved these changes
LGTM!

2020-12-02 12:36 UTC, merged