TRSV2-212: forgot password unhappy path
uktrade/trade-remedies-public pull request #141
Opened 2022-05-24 08:25 UTC by KnowYourLines

2022-05-25 08:45 UTC, chris-pettinga requested changes

2022-05-25 08:45 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/password/reset_password_success.html
> +    <form action="/accounts/password/reset/success/" method="post">
Can you change this to a call to reverse()

2022-05-25 08:45 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/login/login.html
>          $('#show_password').click(function () {
Do we need this here when we have the show_password.js file?

2022-05-25 08:45 UTC, chris-pettinga commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
Why not the client? I know what you mean that it's a separate package which is just an annoying level of abstraction, but how can we deal with password resets on the caseworker side? Do we have to repeat the same call to the API?

2022-05-25 10:34 UTC, KnowYourLines commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
This bit of functionality (requesting a password reset via a user's primary key) is only needed in the design of the public forgotten password journey so far. The journey's design demands a way to request a new reset for a user without entering that user's email address where only the user's primary key is all that's available to identify the user. 

If this functionality was needed in the design on the journey for the caseworker side we could duplicate this call as the caseworker has the same credentials in its [environment variables](https://github.com/uktrade/trade-remedies-caseworker/blob/6f467728c018513238dbc72f26a278de8999245d/trade_remedies_caseworker/config/settings/base.py#L210-L212). 

From what I can tell the [caseworker](https://github.com/uktrade/trade-remedies-caseworker/blob/f2b1810daad982e0f4b7ea33fd54eacddd066f3d/trade_remedies_caseworker/password/views.py) side also just hits the same endpoints and uses the same functions from the client library as the [public](https://github.com/uktrade/trade-remedies-public/blob/0e11db33c5b3fa7678318f6a86074d3952a37cf9/trade_remedies_public/password/views.py) side so I can't see how it would be any different.

2022-05-26 14:41 UTC, holdenweb submitted a review, later dismissed
Needs some changes, the most significant one being the handling of primary key data. Even when PKs are GUUIDs they shouldn't be used in URLs.

Otherwise a useful set of changes. Let's get this in when it's doing what it needs to, and then we can look at a renaming refactoring. Are there many pending branches such renaming might impact?

2022-05-26 14:49 UTC, KnowYourLines commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
Primary keys are already part of many of the URLs on the TRS. I'm just re-using the code that's already part of the TRS.

2022-05-26 14:50 UTC, KnowYourLines commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
Are you suggesting we don't re-use the pre-existing code as planned?

2022-05-26 14:52 UTC, KnowYourLines commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
Happy to rebuild this part of the TRS from scratch of course, but that's not what the original plan for V2 was

2022-05-26 14:56 UTC, KnowYourLines commented on trade_remedies_public/password/views.py
> +        url = f"{API_BASE_URL}/api/v2/accounts/password/pk_request_reset/"
Have been to told explicitly to re-use the existing TRS code as part of V2.

2022-05-26 14:57 UTC, KnowYourLines commented on trade_remedies_public/templates/password/password_reset_requested.html
> +    <p>You will only receive a password reset email if you entered the same email you used to sign up.</p>
Have been to told explicitly to implement the content created in the design prototype as part of V2.

2022-05-26 14:59 UTC, KnowYourLines commented on trade_remedies_public/templates/password/password_reset_requested.html
> +    <p>You will only receive a password reset email if you entered the same email you used to sign up.</p>
Again, this is part of the plan for V2 which is out of my hands.

2022-05-27 17:25 UTC, KnowYourLines commented
The uuid in the password reset email is no longer the uuid representing the user's primary key. It is now a uuid specific to the password reset request.

2022-06-06 09:00 UTC, chris-pettinga approved these changes

2022-06-07 13:41 UTC, merged