V2 Feature - TRSV2-206 - V2 registration journey
uktrade/trade-remedies-public pull request #142
Opened 2022-05-25 16:37 UTC by chris-pettinga

2022-06-09 13:45 UTC, KnowYourLines requested changes

2022-06-09 13:45 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/component_macros/checkbox.html
> +                        <span class="govuk-visually-hidden">Error:</span> {{ error }}
Do these need to be updated for multiple errors being returned from the API?

2022-06-13 11:40 UTC, holdenweb approved these changes
Approved after review module a few small changes.

2022-06-13 11:56 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration/registration_your_uk_employer.html
> +                            populateResults(names)
populateResults is a method exposed by accessibleAutocomplete library imported on line 59

2022-06-13 12:00 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/registration/registration_your_uk_employer.html
> +                            populateResults(names)
Yes thought so, but I can't find any mention of it when doing CTRL+F in `trade_remedies_public/templates/static/v2/js/accessible-autocomplete.min.js`

2022-06-22 10:18 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration/registration_set_password.html
> +        $("#password").keyup(function () {
You're right thanks, fixed

2022-06-22 10:19 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/component_macros/checkbox.html
> +                        <span class="govuk-visually-hidden">Error:</span> {{ error }}
Fields with multiple errors in a list are only returned as part of the error summary box at the top of the page, not for individual errors

2022-06-22 10:20 UTC, merged