TRSV2-208: step2 new client
uktrade/trade-remedies-public pull request #150
Opened 2022-06-22 11:23 UTC by KnowYourLines

2022-06-29 14:34 UTC, chris-pettinga requested changes
Looks good in general and nice abstraction. But some of the built-in django generic class based views aren't exploited to their full advantage. 

a lot of the comments are the same, relating to using get_context_data() instead of get(). and using form_valid and form_invalid() instead of post, then relying on super() calls to render the incorrect form again.

Regarding the HTML templates, all the comments are the same pretty much, if base_with_form.html is too limited and doesn't allow for reuse then let me know and we can work on a solution, but it feels like there must be a way to reduce HTML duplication as it stands.

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/forms.py
> +class NonUkEmployerForm(ValidationForm):
Can we use the NonUkEmployerForm from registration/forms.py

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +                "case_id": case_id,
I would rather use the get_context_data() method to provide updated context dictionary to the template

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +    def post(self, request, case_id=None):
We can use the form_valid() and form_invalid() methods to let the FormMixin/FormView handle validation for us in the backend.

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +    LoginRequiredMixin, GroupRequiredMixin, FormMixin, BasePublicView
Same comment as above

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +        return self.render_to_response(
```suggestion
        return super().form_invalid(form=form)
```
And then override the get_context_data() method of the view to provide the case_id to the context

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +        if not form.is_valid():
use form_valid instead()

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +        return self.render_to_response(
Same as above, use super() and override get_context_data()

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/cases/views.py
> +    def get(self, request, case_id=None, contact_id=None):
If we use FormView instead of FormMixin, we don't need the get() method at all

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/about_your_client.html
> +{% extends "v2/govuk/base.html" %}
Why don't we inherit from base_with_form.html?

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/about_your_client.html
> +{% extends "v2/govuk/base.html" %}
It should mean we don't need to duplicate a lot of this boiler-plate code

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/is_client_uk_company.html
> +{% extends "v2/govuk/base.html" %}
Same comment as above

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/primary_client_contact.html
> +{% extends "v2/govuk/base.html" %}
Same as above

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/who_is_registering.html
> +{% extends "v2/govuk/base.html" %}
same as above

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/who_you_representing.html
> +{% extends "v2/govuk/base.html" %}
same as above

2022-06-29 14:34 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/your_client_details.html
> +{% extends "v2/govuk/base.html" %}
same as above

2022-06-29 14:39 UTC, KnowYourLines commented on trade_remedies_public/cases/forms.py
> +class NonUkEmployerForm(ValidationForm):
The error message is different so don't think so. https://github.com/uktrade/trade-remedies-public/blob/5c84530a31791d7a1b0af1dc31959aacc23a6eb0/trade_remedies_public/registration/forms.py#L107 is `no_name_entered`

2022-06-29 14:44 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/registration_of_interest/about_your_client.html
> +{% extends "v2/govuk/base.html" %}
This template includes a `<div class="govuk-grid-column-full">` which contains a `<span class="govuk-caption-xl">2. About you</span>`. This is placed before the `<div class="govuk-grid-column-two-thirds">` which a subtle but very real difference between this and base_with_form.html

2022-06-29 14:48 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/registration_of_interest/who_is_registering.html
> +{% extends "v2/govuk/base.html" %}
Same reason. Perhaps it's worth creating `base_roi_form.html`?

2022-06-29 14:49 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/registration_of_interest/who_you_representing.html
> +{% extends "v2/govuk/base.html" %}
Same reply as above haha

2022-06-29 14:51 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/registration_of_interest/your_client_details.html
> +{% extends "v2/govuk/base.html" %}
This one is also similar to the previous two, but still different from `base_with_form.html`. I do think we should consider base form templates for each feature/journey rather than than a universal one for the whole TRS, as there is unlikely going to be a one-size fits all form.

2022-06-29 14:57 UTC, KnowYourLines commented on trade_remedies_public/cases/forms.py
> +class YourEmployerForm(ValidationForm):
Yes they are identical, should we have a `core/forms.py` and import from there? Or maybe from `config/forms.py` since it already exists? But then again this isn't really config. Maybe `config/forms.py` should move to `core/forms.py`? What do you think?

2022-06-29 15:26 UTC, chris-pettinga commented on trade_remedies_public/cases/forms.py
> +class YourEmployerForm(ValidationForm):
yes I agree, been thinking about this and config should be reserved for configuration files and base classes I think

2022-06-29 15:26 UTC, chris-pettinga commented on trade_remedies_public/cases/forms.py
> +class NonUkEmployerForm(ValidationForm):
Understood, can you inherit from the form at least and just override that one field?

2022-06-29 15:27 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/is_client_uk_company.html
> +{% extends "v2/govuk/base.html" %}
Understood

2022-06-29 15:29 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration_of_interest/your_client_details.html
> +{% extends "v2/govuk/base.html" %}
WIll just respond to all of them here. Yes I agree in general, there's no point abstracting if you're going to have to change and override the base form so much that it becomes useless, abstracting should be easy and not require thought. Furhtermore, if we're going to duplicate code, it may as well be HTML.

That said however, I'm sure there are things in these base templates (even 1 per feature) that can be done using macros (include) rather than extending base template. Things like the error summaries box at the top of the page that actually relies on what's returned by the API (and so could be vulnerable to change) could be put into a component/macro that is included in each of these templates.

2022-06-29 15:29 UTC, chris-pettinga commented
> Your last comment ends at `Also the tem`, and I'm dying to know what you were trying to say. Or maybe it was nothing?

haha no idea, can't have been that important

2022-06-29 15:56 UTC, KnowYourLines commented on trade_remedies_public/cases/forms.py
> +class NonUkEmployerForm(ValidationForm):
It's 3/5 fields and also the errors raised by cleaning.

2022-06-30 08:44 UTC, KnowYourLines commented on trade_remedies_public/cases/forms.py
> +class NonUkEmployerForm(ValidationForm):
I'm pretty sure they should be different classes.

2022-06-30 12:54 UTC, chris-pettinga approved these changes
Looks great thanks for making the changes.

2022-06-30 13:57 UTC, merged