V2Feature - TRSV2-243 Sign in without verifying email
uktrade/trade-remedies-public pull request #151
Opened 2022-06-22 14:22 UTC by chris-pettinga

2022-06-23 14:26 UTC, KnowYourLines requested changes

2022-06-23 14:26 UTC, KnowYourLines commented on trade_remedies_public/registration/views.py
> +            response = self.trusted_client.send_email_verification_link(kwargs["user_pk"])
Wouldn't the client already have the token to authenticate the user to the API, making the need for passing around the user's primary key in the URL and this request to the API redundant? 

I suspect there is a `request.user.token` or some user token being used to hit the API, which can be used to identify the user for this API request rather than sending over the user's primary key.

2022-06-23 14:32 UTC, KnowYourLines commented
LGTM, depends on how concerned we want to be about the user uuid being passed around in URLs.

2022-06-23 14:34 UTC, KnowYourLines commented on trade_remedies_public/templates/v2/login/login.html
> +{% block back_button %}{% endblock back_button %}
Ah makes sense, we just override with a blank block so there's no back button and we don't have to do dodgy `NON_BACK_URLS` in the middleware.

2022-06-27 11:18 UTC, holdenweb approved these changes
Yes, get it merged!

2022-06-27 11:20 UTC, KnowYourLines approved these changes

2022-06-27 11:45 UTC, merged