TRSv2-316 - Clear data when company search text removed
uktrade/trade-remedies-public pull request #186
Opened 2022-08-18 15:26 UTC by nahmed99

2022-08-19 15:21 UTC, chris-pettinga commented
We need to do the same with the code from the registration journey

2022-08-22 12:48 UTC, chris-pettinga requested changes

2022-08-22 12:48 UTC, chris-pettinga commented on trade_remedies_public/templates/v2/registration/registration_your_uk_employer.html
> +                        $("#v2-registration-your-organisation-form").submit(function () {
you don't need this additional code as the registration journey gets the company data from the JSON value that is put as the value of the $('[name=company_data]') field

2022-08-22 13:57 UTC, nahmed99 commented on trade_remedies_public/templates/v2/registration/registration_your_uk_employer.html
> +                        $("#v2-registration-your-organisation-form").submit(function () {
Replaced.

2022-08-22 14:21 UTC, chris-pettinga approved these changes

2022-08-22 14:25 UTC, merged