BDD test of login
uktrade/trade-remedies-public pull request #24
Opened 2020-12-23 15:41 UTC by Luisella21

2020-12-24 13:09 UTC, davecharles requested changes
Really good start. I have a couple of comments. Also, can we work together to add `pytest` fixtures? I think it will benefit the construction and future maintenance of these tests.

2020-12-24 13:09 UTC, davecharles commented on trade_remedies_public/features/steps/utils.py
> +    return WebDriverWait(context.browser, 500).until(ec.presence_of_element_located((By.ID, id)))
`WebDriverWait` duration is in seconds, so maybe make this a brisk 10 seconds (the `until` will mitigate this). Also, if the wait expires [it'll raise a timeout exception](https://selenium-python.readthedocs.io/waits.html#explicit-waits) so I'm thinking you should encapsulate in `try/except TimeoutException as e:` and `assert False` in the except clause or perhaps:

```python
pytest.fail(f"timed out waiting for element {id}")
```

2020-12-24 13:09 UTC, davecharles commented on trade_remedies_public/features/steps/login.py
> +# from features.api_test_objects import create_test_object
We should remove this if not used

2020-12-24 13:09 UTC, davecharles commented on trade_remedies_public/features/api_test_objects.py
> +def create_test_user(email, password, group):
I'd love to start using `pytest` fixtures now, I think the time is right! I can help you add these.

2020-12-24 13:09 UTC, davecharles commented on trade_remedies_public/features/steps/shared.py
> +    print("In When")
We can probably remove this now you've proven it works.

2020-12-29 13:28 UTC, Luisella21 commented on trade_remedies_public/templates/registration/login.html
> +    <button type="submit" id="bdd-submit" class="button margin-top-2" name="btn-action" value="login" >Sign in</button>
Changed to login-submit.

2020-12-29 13:29 UTC, Luisella21 commented on trade_remedies_public/features/steps/shared.py
> +    print("In When")
Forgotten in...

2020-12-29 13:33 UTC, Luisella21 commented on trade_remedies_public/features/steps/utils.py
> +    return WebDriverWait(context.browser, 500).until(ec.presence_of_element_located((By.ID, id)))
Changed the timeout to 10seconds.

2021-01-06 16:26 UTC, davecharles approved these changes
Really good start. I have a couple of comments. Also, can we work together to add `pytest` fixtures? I think it will benefit the construction and future maintenance of these tests.

2021-01-06 16:26 UTC, davecharles commented on trade_remedies_public/features/fixtures.py
> +    context.password = TEST_PASSWORD
I get that we're creating the test object remotely on the API, just wondering if (for readability etc) we should return a representative value (and also return context.[value] in `before_tag` `after_scenario` etc), just wondering it it might help with debugging the tests.

2021-01-06 16:51 UTC, Luisella21 commented on trade_remedies_public/features/fixtures.py
> +    context.password = TEST_PASSWORD
Good idea.

2021-01-06 17:33 UTC, merged