Feature/trsv2449 update v1 public dashboard to cater new invitation journey statues
uktrade/trade-remedies-public pull request #269
Opened 2023-02-08 08:43 UTC by osimuka

2023-02-08 09:11 UTC, nahmed99 commented on trade_remedies_public/templates/dashboard.html
> +                            <li><a class="link bold" href="{% url 'manage-users' %}">Manage users</a>
This is before the user has done anything (after first registration). On ticket TRSv2-449 (comments), Nick stated that there is no need to change this.

2023-02-09 10:23 UTC, merged

2023-02-09 10:25 UTC, chris-pettinga requested changes

2023-02-09 10:25 UTC, chris-pettinga commented on trade_remedies_public/core/views.py
>              invitation_type=2,
we need to get both own-org and representative invites but NOT caseworker invites. SO basically any invitation that is invitation_type either 1 or 2

2023-02-09 10:25 UTC, chris-pettinga commented on trade_remedies_public/core/views.py
>          if organisation:
we should check first that the current logged-in user is an admin of their organisation before we bother to do this.

2023-02-09 10:25 UTC, chris-pettinga commented on trade_remedies_public/templates/dashboard.html
> +                        {% if is_org_owner or pending_invitation_count or pending_invitation_deficient_docs_count or pending_invitation_waiting_trs_approval_count %}
org_owner needs to be always True, so 
```suggestion
                        {% if is_org_owner and pending_invitation_count or pending_invitation_deficient_docs_count or pending_invitation_waiting_trs_approval_count %}
```