TRSv2-491 - Request organisation details for rep from new org
uktrade/trade-remedies-public pull request #273
Opened 2023-02-10 15:29 UTC by nahmed99

2023-02-10 16:31 UTC, osimuka approved these changes

2023-02-15 15:03 UTC, chris-pettinga requested changes

2023-02-15 15:03 UTC, chris-pettinga commented on trade_remedies_public/cases/v2_views/accept_representative_invitation.py
> +            return redirect(
We need to move the if statement down here. We still want all the above stuff to happen if the organisation has just been created. The only difference is where we go next.

2023-02-15 15:24 UTC, nahmed99 commented on trade_remedies_public/cases/v2_views/accept_representative_invitation.py
> +            return redirect(
Most of the stuff above this point will happen in the two classes below (that's where this code was copied from) - while we are gathering the organisation (+additional) details - for the new organisation.

I know that there is duplication of code. Perhaps another method to merge some of that code?

2023-02-15 15:37 UTC, chris-pettinga commented on trade_remedies_public/cases/v2_views/accept_representative_invitation.py
> +            return redirect(
hmm

2023-02-15 15:43 UTC, chris-pettinga commented on trade_remedies_public/cases/v2_views/accept_representative_invitation.py
> +            return redirect(
ok looking at the view, it seems like I have scattered the invitation processing stuff around pretty poorly. So let's shelve that for another ticket and go ahead with the duplication for the moment so we can push this through to UAT

2023-02-15 15:43 UTC, chris-pettinga approved these changes

2023-02-17 09:42 UTC, merged