BDD tests for the first phase of Third Party invite.
uktrade/trade-remedies-public pull request #28
Opened 2021-01-22 11:20 UTC by Luisella21

2021-01-22 11:36 UTC, rossmiller requested changes
Looks good. Some very minor changes requested.

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/features/steps/utils.py
> +def testuser_login(context):
Could we make the func name `test_user_login` ?

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/features/steps/utils.py
> +# def create_test_user(context):
Should this be removed?

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/features/third_party/invite.feature
> +  Scenario: The user access the 'Manage your team' page
The user accesses the 'Manage your team' page

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/features/third_party/invite.feature
> +  Scenario: The user select a case for the third party invite,
The user selects a case for the third party invite (remove trailing comma)

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/templates/account/team.html
> +      <a class="button margin-top-1" id="bdd_invite_colleague" href="/accounts/team/{{user.organisation.id}}/user/">Invite a colleague</a>
Can we amend the URL to use reverse?

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/templates/account/user-edit-base.html
> +				<button type="submit" id="submit" class="button" value="save">Continue</button>
Do you need the `bdd_` prefix? If not does it need to removed elsewhere?

2021-01-22 11:36 UTC, rossmiller commented on trade_remedies_public/templates/account/user-edit-base.html
> +				<button type="submit" id="submit" class="button pull-left" value="save">Save</button>
As above.

2021-01-22 11:49 UTC, Luisella21 commented on trade_remedies_public/templates/account/user-edit-base.html
> +				<button type="submit" id="submit" class="button" value="save">Continue</button>
Added prefix.

2021-01-22 12:06 UTC, Luisella21 commented on trade_remedies_public/templates/account/team.html
> +      <a class="button margin-top-1" id="bdd_invite_colleague" href="/accounts/team/{{user.organisation.id}}/user/">Invite a colleague</a>
Can we do it in a different PR?

2021-01-22 12:40 UTC, davecharles reviewed
Couple of observations :)

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/templates/account/team.html
> +      <a class="button margin-top-1" id="bdd_invite_colleague" href="/accounts/team/{{user.organisation.id}}/user/">Invite colleague</a>
The id should just be a sensible name, I don't think it needs to be prefixed `bdd_`

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/templates/account/user-edit-base.html
> +				<button type="submit" id="bdd_submit" class="button" value="save">Continue</button>
As before - maybe just `btn_submit`

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/templates/account/user-edit-base.html
> +				<button type="submit" id="bdd_submit" class="button pull-left" value="save">Save</button>
As before - maybe just `btn_submit`

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/templates/dashboard.html
> +              {% if pre_manage_team and is_org_owner %}<li><a href="/accounts/team/" id="bdd_manage_your_team">Manage your team</a></li>{% endif %}
As before - maybe just `lnk_manage_your_team`

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/features/environment.py
> +from features.steps.utils import (
Just a thought - this import list will get larger ass we add more utils, also it'll be clearer to the future reader where a util originates, so maybe:
```python
import features.steps.utils as utils
...
utils.go_to_page(...)
```

2021-01-22 12:40 UTC, davecharles commented on trade_remedies_public/features/steps/third_party.py
> +    ref = get_element_by_id(context, "bdd_manage_your_team")
As above, to make this better for future reader, change the import and say:
```python
utils.get_element_by_id(...)
```

2021-01-25 11:54 UTC, rossmiller commented on trade_remedies_public/features/environment.py
> +from features.steps.utils import (
@davecharles I would say that the `utils.foo` style is useful if the package/namespace adds to the understanding of the function and not if it doesn't. IMO `go_to_page` is self explanatory and doesn't require qualification.

2021-01-25 11:55 UTC, rossmiller commented on trade_remedies_public/templates/account/team.html
> +      <a class="button margin-top-1" id="bdd_invite_colleague" href="/accounts/team/{{user.organisation.id}}/user/">Invite colleague</a>
@davecharles I suggested the prefix so we know that the attribute is there because of the BDD tests. ids are not generally used but you are right - it's not necessary, and perhaps is more confusing than helpful overall.

2021-01-26 17:23 UTC, davecharles approved these changes
LGTM!

2021-01-26 17:42 UTC, rossmiller commented on trade_remedies_public/features/third_party/invite.feature
> +  Scenario: The user select a case for the third party invite,
@Luisella21 looks like you still need to address the above ^^

2021-01-27 09:47 UTC, rossmiller approved these changes
LGTM!

2021-01-27 09:49 UTC, merged