Add document metadata extraction
uktrade/trade-remedies-public pull request #308
Opened 2023-03-28 15:29 UTC by yusufsheiqh

## Context

- Add custom file upload handler to extract metadata from uploaded documents

2023-03-28 16:00 UTC, chris-pettinga requested changes

2023-03-28 16:00 UTC, chris-pettinga commented on trade_remedies_public/documents/tests.py
> +class ExtractDocumentMetadataTestCase(TestCase):
Does this class not need to begin with the word Test?

2023-03-28 16:00 UTC, chris-pettinga commented on trade_remedies_public/documents/upload_handler.py
> +        if len(raw_data) > 31457280:  # 30 Megabytes
Please put this in the config/base.py, reading from an environment variable with a default of 31457280 so we can change it in the future if we want. _not like there's much of a future..._

2023-03-28 16:00 UTC, chris-pettinga commented on trade_remedies_public/documents/views.py
> +            error_message = "The selected file must be smaller than 30MB"
We are duplicating the error_message here, I understand it's because we're skipping the file but it seems wasteful. Can we not throw a breaking exception that we then catch here and return the 400 response with?

2023-03-28 16:00 UTC, chris-pettinga commented on trade_remedies_public/documents/views.py
> +    def construct_error_summary_message(request, file_type):
There is a function in config/utils.py that does exactly this - def add_form_error_to_session

2023-03-28 16:08 UTC, yusufsheiqh commented on trade_remedies_public/documents/tests.py
> +class ExtractDocumentMetadataTestCase(TestCase):
Doesn't seem like it. This is using [Django's TestCase](https://docs.djangoproject.com/en/4.1/topics/testing/overview/#writing-tests), but it also seems like `pytest` is clever enough to figure it out.

2023-03-28 16:24 UTC, yusufsheiqh commented on trade_remedies_public/documents/upload_handler.py
> +        if len(raw_data) > 31457280:  # 30 Megabytes
Resolved in https://github.com/uktrade/trade-remedies-public/pull/308/commits/dedd09bcfa204bc5bbb21e3390062a626d3cfde4.

2023-03-29 09:16 UTC, yusufsheiqh commented on trade_remedies_public/documents/views.py
> +            error_message = "The selected file must be smaller than 30MB"
No, sadly. The upload handler only gets evoked when we access `request.FILES`. However, I have created a constant for the error message, so it only needs to be changed in one place.

2023-03-29 09:17 UTC, yusufsheiqh commented on trade_remedies_public/documents/views.py
> +            error_message = "The selected file must be smaller than 30MB"
Resolved in https://github.com/uktrade/trade-remedies-public/pull/308/commits/afe78a286ee058ec5ea74aaefa9f10292ca146ae.

2023-03-29 09:33 UTC, yusufsheiqh commented on trade_remedies_public/documents/views.py
> +        error_message = "The selected file must be smaller than 30MB"
Resolved in https://github.com/uktrade/trade-remedies-public/pull/308/commits/f5d8777b8c45f609832b7864c97388115255d429.

2023-03-29 10:27 UTC, chris-pettinga approved these changes

2023-03-29 10:28 UTC, chris-pettinga commented on trade_remedies_public/config/settings/base.py
> +FILE_MAX_SIZE_BYTES = 31457280
I think should be an environment variable so we can test and change between environments going forward.

```suggestion
FILE_MAX_SIZE_BYTES = env.int("FILE_MAX_SIZE_BYTES", default=31457280)
```

2023-03-29 10:43 UTC, yusufsheiqh commented on trade_remedies_public/config/settings/base.py
> +FILE_MAX_SIZE_BYTES = 31457280
Resolved in https://github.com/uktrade/trade-remedies-public/pull/308/commits/0e4caf69cf2b42d20338a9a8e6781523b336904c.

2023-03-29 13:23 UTC, chris-pettinga approved these changes

2023-04-11 08:50 UTC, nahmed99 approved these changes

2023-04-12 10:33 UTC, merged