feat: trlst-216 Allow to remove mismatches files
uktrade/trade-remedies-public pull request #36
Opened 2021-02-26 08:28 UTC by Luisella21

2021-02-26 14:23 UTC, Luisella21 commented
Normally a public user can only upload a confidential file, followed by the corresponding non-confidential version.
A user managed to upload an extra non-confidential file (possibly by uploading from two different windows). 
The extra file is stops him from completing the submission, but there is no provision to remove it.
Added an extra category when showing the uploaded file. The category lists the single non-confidential version, and ask the user to remove it. The interface allows to download the file before deleting it.
![image](https://user-images.githubusercontent.com/36708790/109311811-293b7500-783e-11eb-8f8b-8f585e22664f.png)

2021-02-26 14:26 UTC, rossmiller submitted a review, later dismissed
One very minor point!

2021-02-26 14:26 UTC, rossmiller commented on trade_remedies_public/cases/utils.py
> +    parent_idx = deep_index_items_by(conf_idx.get("false", []), "parent_id")
Could you give this a more meaningful name?

2021-02-26 14:41 UTC, davecharles requested changes
See comments

2021-02-26 14:41 UTC, davecharles commented on trade_remedies_public/cases/utils.py
> +    parent_idx = deep_index_items_by(conf_idx.get("false", []), "parent_id")
So maybe:
```python
document_types = ...
confidential_docs = ...
all_docs_by_id = ...
doc_parents = ...
```

2021-02-26 14:53 UTC, Luisella21 commented on trade_remedies_public/cases/utils.py
> +    parent_idx = deep_index_items_by(conf_idx.get("false", []), "parent_id")
Thank you Dave, very good suggestion!

2021-03-01 11:07 UTC, davecharles approved these changes
LGTM

2021-03-01 14:00 UTC, merged