Feature - TSS-925 - Public file updates
uktrade/trade-remedies-public pull request #364
Opened 2023-09-14 15:11 UTC by chris-pettinga

2023-09-18 10:21 UTC, osimuka requested changes

2023-09-18 10:21 UTC, osimuka commented on requirements.in/base.in
> +whitenoise==5.3.0
new line

2023-09-18 10:21 UTC, osimuka commented on requirements.in/dev.in
> +git+https://github.com/uktrade/fitness-functions
new line

2023-09-18 10:21 UTC, osimuka commented on requirements.in/prod.in
> +gunicorn==20.0.4
new line

2023-09-20 08:56 UTC, Santino-Trade approved these changes

2023-09-20 09:35 UTC, ferozerub approved these changes

2023-09-21 08:14 UTC, merged